version: '3.7'

networks:
    app:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - '8080:80'
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - app
    
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: local
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/lib/html
        ports:
            - '9000:9000'
        networks:
            - app